#!/bin/zsh

source $HOME/.profile

ping -q -w 1 -c 1 8.8.8.8 || exit

cat $XDG_CONFIG_HOME/alarms/locks/twitter_checklock && exit
cat $XDG_CONFIG_HOME/alarms/locks/computer_locked && exit

oldsum=$(cat $XDG_CONFIG_HOME/i3/alarms/twitter | awk '{print $1}')
newsum=$(twitter --oauth=$XDG_CONFIG_HOME/.twitter_oauth replies | sha512sum | awk '{print $1}')

[[ "$oldsum" = "$newsum" ]] && exit

echo $newsum > $XDG_CONFIG_HOME/i3/alarms/twitter
