#!/bin/zsh

xrdb $XDG_CONFIG_HOME/xserver/Xresources

[ -z "$1" ] || wal -i $1
[ -z "$1" ] && [ "$1" = "transparent" ] || wal -f $XDG_CACHE_HOME/wal/colors

[ -z "$2" ] && [ "$2" = "transparent" ] && wal -a 85 -f $XDG_CACHE_HOME/wal/colors
[ -z "$1" ] && [ "$1" = "transparent" ] && wal -a 85 -f $XDG_CACHE_HOME/wal/colors

source "$XDG_CACHE_HOME/wal/colors.sh"

background=${color0:1}
foreground=${color14:1}

oomoxconf="/tmp/autotheme"

cat << HEREDOC > $oomoxconf
NAME="autotheme"
BG=$background
FG=$foreground
TXT_BG=$background
TXT_FG=$foreground
MENU_BG=$background
MENU_FG=$foreground
SEL_BG=$foreground
SEL_FG=$background
BTN_BG=$background
BTN_FG=$foreground
HEREDOC

oomox-cli $oomoxconf -t $XDG_DATA_HOME/themes

tmpbgbak="$XDG_CONFIG_HOME/xlock/screen.png"
tmpbg="$(cut -d\' -f2 ~/.fehbg | sed -n 2p)"
export MAGICK_OCL_DEVICE=OFF

echo Updating zathura config files...
$XDG_CONFIG_HOME/zathura/.rcgen > $XDG_CONFIG_HOME/zathura/zathurarc
echo Done.
echo Updating dunst config files...
$XDG_CONFIG_HOME/dunst/.rcgen > $XDG_CONFIG_HOME/dunst/dunstrc
echo Restarting dunst...
pgrep dunst && killall dunst
eval $(dbus-launch)
echo Done.
echo Lock screen
cp "$tmpbg" "$tmpbgbak"
echo Resizing and croping...
convert "$tmpbgbak" -resize 1920x1080^ -gravity center -extent 1920x1080 "$tmpbgbak" 
echo Bluring...
convert "$tmpbgbak" -blur 0x6 "$tmpbgbak"
echo Done.

