source ~/.profile
export __GL_SHADER_DISK_CACHE_PATH=~/.cache/nv/
export ERRFILE=~/.config/xserver/xsessions-errors
export DWMSCRIPTS=/usr/local/bin/scripts/dwm

xrandr --dpi 96
setxkbmap fr
~/.fehbg &
xrdb -I$XDG_CACHE_HOME $XDG_CONFIG_HOME/xserver/Xresources
xcompmgr -f -D5 &
pgrep dwmblocks || dwmblocks &
killall -9 dunst
dunst &
pgrep pulseaudio || pulseaudio --daemonize
pgrep mpd$ || mpd &
pgrep mpdscribble || mpdscribble &
pgrep mpdiscord || mpdiscord &
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
yams
numlockx on
dwm
