source ~/.profile
export __GL_SHADER_DISK_CACHE_PATH=~/.cache/nv/
export ERRFILE=~/.config/xserver/xsessions-errors
export DWMSCRIPTS=/usr/local/bin/scripts/dwm
#export XAUTHORITY=~/.config/xserver/Xauthority
setxkbmap fr
~/.fehbg
xrdb -I$XDG_CACHE_HOME $XDG_CONFIG_HOME/xserver/Xresources
dwmblocks &
xcompmgr -f -D5 &
killall -9 dunst
dunst &
numlockx
dwm
