blur-background = false;
blur-background-frame = true;
blur-background-fixed = true;

blur-background-exclude = [ 
    "!class_g *?= 'st'"
  ];

blur :
{
  method = "dual_kawase";
  size = 1.0;
  strength = 6.0;
  deviation=1.0;
};

corner-radius = 20

rounded-corners-exclude = "!class_g ?= 'st' || class_g ?= 'rofi'";
