#!/bin/sh

source $XDG_CACHE_HOME/wal/colors.sh

link="$1"

handler=$(echo -e "firefox\nchromium\nmpv" | rofi -dmenu -i -p "Choose a link handler" \
-font "Whatever 18" -lines 3 -hide-scrollbar -color-window "$color0,$color7,$color1")

[ "$link" ] && [ "$handler" ] && $handler "$link"
