#!/bin/bash

if [ "$1" = "sel" ]; then
    notify-send -u low "Screenshot" "Please select a window or rectangular area." -t 1000
    sleep 1
  if [ -z "$2" ]; then
      scrot '%Y%m%d-%H%M%S.png' -s -e 'mv $f ~/Media/Screenshots/Misc/; \
      notify-send -u low "Saved screenshot" "$f"' \
      && exit
  else
    scrot '%Y%m%d-%H%M%S.png' -s -e 'xclip -t image/png -selection clipboard -i $f; \
      rm $f; \
      notify-send -u low "Took screenshot" "Copied it to clipboard."' 
  fi
else
  if [ -z "$2" ]; then
#   scrot '%Y%m%d-%H%M%S.png' -e 'mv $f ~/Media/Screenshots/Misc; \
    scrot '%Y%m%d-%H%M%S.png' -e 'mv $f ~/Media/Screenshots/Cours/; \
      notify-send -u low "Saved screenshot" "$f"' \
      && exit
  else
    scrot '%Y%m%d-%H%M%S.png' -e 'xclip -t image/png -selection clipboard -i $f; \
      rm $f; \
      notify-send -u low "Took screenshot" "Copied it to clipboard."' 
  fi
fi
