#!/bin/sh

source $XDG_CACHE_HOME/wal/colors.sh

answer=$(echo -e "Restart i3\nExit i3\nSuspend\nReboot\nShutdown" | rofi \
-dmenu -i -p "Shutdown options" -lines 5 -hide-scrollbar -font "Whatever 18" \
-color-window "$color0,$color7,$color1")

[ -z "$answer" ] && exit

case "$answer" in
  "Exit i3") i3-msg exit ;;
  "Restart i3") i3-msg restart ;;
  "Suspend") $XDG_CONFIG_HOME/i3/scripts/lock & systemctl suspend ;;
  "Reboot") $XDG_CONFIG_HOME/i3/scripts/prompt "Reboot" && systemctl reboot ;;
  "Shutdown") $XDG_CONFIG_HOME/i3/scripts/prompt "Shutdown" && systemctl poweroff ;;
esac
