#!/bin/zsh

case $BLOCK_BUTTON in
  1) mpc toggle > /dev/null ;;
  2) mpc prev > /dev/null ;;
  3) mpc next > /dev/null ;;
# 2) mpc stop > /dev/null ;;
# 3) i3-msg "workspace \"5:♫ \"; exec urxvt -e ncmpcpp" >> /dev/null ;;
  4) mpc volume +2 > /dev/null ;;
  5) mpc volume -2 > /dev/null ;;
esac

for i in $(mpc --format ""); do
    a=$i
    break
done

if [ $a = "[playing]" ] ; then
  echo -ne " "
elif [ $a = "[paused]" ] ; then
  echo -ne " "
#else
#  echo -ne " 🎵"
fi

current=`mpc current | tr -d '\n\r'`
echo ${current:0:70}
