#!/bin/sh

source $XDG_CACHE_HOME/wal/colors.sh
source ~/.profile # temp until Xserver restart

n=$(ls $ADMINSCRIPTS/powerplans | wc -l)
[ $n -gt 5 ] && n=5

answer=$(ls $ADMINSCRIPTS/powerplans/ | rofi -dmenu -i -p "Use powerplan" -lines $n \
  -hide-scrollbar -font "Whatever 18" -color-window "$color0,$color7,$color1")

[ -z "$answer" ] \
  || (zenity --password --text "Applying powerplan: $answer" | sudo -S "$ADMINSCRIPTS/powerplans/$answer" 2>/dev/null) \
  || notify-send -u low "sudo" "Wrong Password"

exit
