#!/bin/bash

report=$(acpi -t | awk '{print "Global: +" $4 "°C\\n"}')
report+=$(sensors | grep Core | awk '{print "CPU", $2, $3}')
report+=$(nvidia-smi -q -d TEMPERATURE | grep "GPU Current" | awk '{print "\\nGPU: +" $5 ".0°C\\n"}')
report+=$(sensors | grep cpu_fan | awk '{print "Fan speed:", $2, "RPM\\n"}')
report+=$(cpupower frequency-info | grep -e "current CPU frequency.*Hz" | awk '{print "CPU frequency: " $4 $5}')
#report+=$(nbfc status 2>/dev/null | grep "Service enabled" | awk '{print "\nNBFC enabled : " $4}')

case $BLOCK_BUTTON in
  1) notify-send -u low "Performance report" "$report" ;;
  2) $XDG_CONFIG_HOME/i3/scripts/select_powerplan 2>&1 /dev/null & ;;
  3) $XDG_CONFIG_HOME/i3/scripts/fan_control 2>&1 /dev/null & ;;
esac > /dev/null

acpi -t | awk '{print $4 "°C"}'
